/*
 * WARNING: There is nothing in this file for students to edit or change.
 *          This file is intended to have no student-serviceable code.
 *
 * "Draw" your GUI using the "Design" tab, and remember to give
 * them memorable variable names in the "Properties" panel
 * as well as make them public variables.
 * 
 * For convenience, you may want to set the default visibility of 
 * GUI elements to be public by going to:
 *    The NetBeans Preferences or Settings menu -> Miscellaneous -> GUI Builder
 * Then set Variables Modifier to public.
 */
package cs20viewcontroller;

import cs20models.AllModelsForView;

/**
 * WARNING: Do NOT modify or write any code in this file!
 *
 * @author cheng
 */
public class DrawnView extends AllModelsForView {
    // WARNING: Do NOT modify or write any code in this file!
    // <editor-fold defaultstate="collapsed" desc="Generated Code">

    public DrawnView() {
        initComponents();
    }// </editor-fold>

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        colorModeButtonGroup = new javax.swing.ButtonGroup();
        typingPanelHostPanel = new javax.swing.JPanel();
        keyboardPanel = new javax.swing.JPanel();
        labelLeftCtrl = new javax.swing.JLabel();
        labelSpace = new javax.swing.JLabel();
        labelRightCtrl = new javax.swing.JLabel();
        labelWindows = new javax.swing.JLabel();
        labelFn = new javax.swing.JLabel();
        labelEnter = new javax.swing.JLabel();
        labelRightAlt = new javax.swing.JLabel();
        labelLines = new javax.swing.JLabel();
        labelLeftAlt = new javax.swing.JLabel();
        labelV = new javax.swing.JLabel();
        labelB = new javax.swing.JLabel();
        labelN = new javax.swing.JLabel();
        labelM = new javax.swing.JLabel();
        labelComma = new javax.swing.JLabel();
        labelPeriod = new javax.swing.JLabel();
        labelF = new javax.swing.JLabel();
        labelRightShift = new javax.swing.JLabel();
        labelApostrophe = new javax.swing.JLabel();
        labelSemicolon = new javax.swing.JLabel();
        labelL = new javax.swing.JLabel();
        labelK = new javax.swing.JLabel();
        labelJ = new javax.swing.JLabel();
        labelH = new javax.swing.JLabel();
        labelG = new javax.swing.JLabel();
        labelC = new javax.swing.JLabel();
        labelX = new javax.swing.JLabel();
        labelZ = new javax.swing.JLabel();
        labelD = new javax.swing.JLabel();
        labelS = new javax.swing.JLabel();
        labelBackSlash = new javax.swing.JLabel();
        labelLeftShift = new javax.swing.JLabel();
        labelW = new javax.swing.JLabel();
        labelE = new javax.swing.JLabel();
        labelR = new javax.swing.JLabel();
        labelT = new javax.swing.JLabel();
        labelY = new javax.swing.JLabel();
        labelU = new javax.swing.JLabel();
        labelI = new javax.swing.JLabel();
        labelO = new javax.swing.JLabel();
        labelP = new javax.swing.JLabel();
        labelOpenBracket = new javax.swing.JLabel();
        labelCloseBracket = new javax.swing.JLabel();
        labelA = new javax.swing.JLabel();
        labelBefore1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        label8 = new javax.swing.JLabel();
        label9 = new javax.swing.JLabel();
        label0 = new javax.swing.JLabel();
        labelMinus = new javax.swing.JLabel();
        labelEquals = new javax.swing.JLabel();
        labelBackspace = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        labelQ = new javax.swing.JLabel();
        labelTab = new javax.swing.JLabel();
        labelCaps = new javax.swing.JLabel();
        labelSlash = new javax.swing.JLabel();
        keyboardKeysPanel = new javax.swing.JPanel();
        leftPalmPanel = new javax.swing.JPanel();
        leftPinkiePanel = new javax.swing.JPanel();
        leftRingPanel = new javax.swing.JPanel();
        leftMiddlePanel = new javax.swing.JPanel();
        leftPointerPanel = new javax.swing.JPanel();
        leftThumbPanel = new javax.swing.JPanel();
        rightPalmPanel = new javax.swing.JPanel();
        rightThumbPanel = new javax.swing.JPanel();
        rightPointerPanel = new javax.swing.JPanel();
        rightMiddlePanel = new javax.swing.JPanel();
        rightRingPanel = new javax.swing.JPanel();
        rightPinkiePanel = new javax.swing.JPanel();
        typingPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        colorTextPane = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        textPaneArea = new javax.swing.JTextPane();
        wpmLabel = new javax.swing.JLabel();
        tipsLabel = new javax.swing.JLabel();
        sentenceRadioButton = new javax.swing.JRadioButton();
        uppercaseRadioButton = new javax.swing.JRadioButton();
        lowercaseRadioButton = new javax.swing.JRadioButton();
        symbolRadioButton = new javax.swing.JRadioButton();
        numberRadioButton = new javax.swing.JRadioButton();
        userTextField = new javax.swing.JTextField();
        clickAboveLabel = new javax.swing.JLabel();
        customTextRadioButton = new javax.swing.JRadioButton();
        trueAccuracyLable = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginSignUpPanel = new javax.swing.JPanel();
        passwordField = new javax.swing.JPasswordField();
        usernameField = new javax.swing.JTextField();
        loginSignUpLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        signUpButton = new javax.swing.JButton();
        settingsPanel = new javax.swing.JPanel();
        lightModeRadioButton = new javax.swing.JRadioButton();
        darkModeRadioButton = new javax.swing.JRadioButton();
        stringLengthSlider = new javax.swing.JSlider();
        stringLengthSliderLabel = new javax.swing.JLabel();
        typingSoundsVolumeSlider = new javax.swing.JSlider();
        typingSoundsVolumeSliderLabel = new javax.swing.JLabel();
        textDisplaySizeSlider = new javax.swing.JSlider();
        textDisplaySizeSliderLabel = new javax.swing.JLabel();
        typedTextSizeSliderLabel = new javax.swing.JLabel();
        typedTextSizeSlider = new javax.swing.JSlider();
        errorSoundsVolumeSliderLabel = new javax.swing.JLabel();
        errorSoundsVolumeSlider = new javax.swing.JSlider();
        lofiStreamVolumeSliderLabel = new javax.swing.JLabel();
        lofiStreamVolumeSlider = new javax.swing.JSlider();
        streamLofiButton = new javax.swing.JToggleButton();
        resetSettingsButton = new javax.swing.JButton();
        keyboardVisualRadioButton = new javax.swing.JRadioButton();
        customTextPanel = new javax.swing.JPanel();
        customTextLabel = new javax.swing.JLabel();
        customTextButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        customTextTextArea = new javax.swing.JTextArea();
        descriptionLabel = new javax.swing.JLabel();
        logoutPanel = new javax.swing.JPanel();
        logoutButton = new javax.swing.JButton();
        savePreferencesButton = new javax.swing.JButton();
        buttonGroupPanel = new javax.swing.JPanel();
        shapePanel = new javax.swing.JPanel();
        loginSignUpButton = new javax.swing.JToggleButton();
        settingsButton = new javax.swing.JToggleButton();
        getNewTextButton = new javax.swing.JButton();
        customTextPanelButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new java.awt.FlowLayout());

        typingPanelHostPanel.setBackground(new java.awt.Color(51, 255, 255));

        keyboardPanel.setBackground(new java.awt.Color(255, 0, 102));
        keyboardPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelLeftCtrl.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        labelLeftCtrl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLeftCtrl.setText("CTRL");
        labelLeftCtrl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
        keyboardPanel.add(labelLeftCtrl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 70, 50));

        labelSpace.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        labelSpace.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSpace.setText("Space");
        labelSpace.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
        keyboardPanel.add(labelSpace, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 290, -1));

        labelRightCtrl.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        labelRightCtrl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRightCtrl.setText("CTRL");
        labelRightCtrl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
        keyboardPanel.add(labelRightCtrl, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 380, 90, 50));

        labelWindows.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        labelWindows.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWindows.setText("WIN");
        labelWindows.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
        keyboardPanel.add(labelWindows, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 50, 50));

        labelFn.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        labelFn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFn.setText("FN");
        labelFn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
        keyboardPanel.add(labelFn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 50, 50));

        labelEnter.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        labelEnter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEnter.setText("ENTER");
        labelEnter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
        keyboardPanel.add(labelEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 260, 110, 50));

        labelRightAlt.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        labelRightAlt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRightAlt.setText("ALT");
        labelRightAlt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
        keyboardPanel.add(labelRightAlt, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 50, 50));

        labelLines.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        labelLines.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLines.setText("--");
        labelLines.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
        keyboardPanel.add(labelLines, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 50, 50));

        labelLeftAlt.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        labelLeftAlt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLeftAlt.setText("ALT");
        labelLeftAlt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
        keyboardPanel.add(labelLeftAlt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 50, 50));

        labelV.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        labelV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelV.setText("V");
        labelV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
        keyboardPanel.add(labelV, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 50, 50));

        labelB.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        labelB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelB.setText("B");
        labelB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
        keyboardPanel.add(labelB, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 50, 50));

        labelN.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        labelN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelN.setText("N");
        labelN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
        keyboardPanel.add(labelN, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 50, 50));

        labelM.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        labelM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelM.setText("M");
        labelM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
        keyboardPanel.add(labelM, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 50, 50));

        labelComma.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        labelComma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelComma.setText(",");
        labelComma.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
        keyboardPanel.add(labelComma, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 50, 50));

        labelPeriod.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        labelPeriod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPeriod.setText(".");
        labelPeriod.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
        keyboardPanel.add(labelPeriod, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, 50, 50));

        labelF.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        labelF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelF.setText("F");
        labelF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
        keyboardPanel.add(labelF, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 50, 50));

        labelRightShift.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        labelRightShift.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRightShift.setText("SHIFT");
        labelRightShift.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
        keyboardPanel.add(labelRightShift, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 320, 80, 50));

        labelApostrophe.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        labelApostrophe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelApostrophe.setText("'");
        labelApostrophe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
        keyboardPanel.add(labelApostrophe, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, 50, 50));

        labelSemicolon.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        labelSemicolon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSemicolon.setText(";");
        labelSemicolon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
        keyboardPanel.add(labelSemicolon, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, 50, 50));

        labelL.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        labelL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelL.setText("L");
        labelL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
        keyboardPanel.add(labelL, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 50, 50));

        labelK.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        labelK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelK.setText("K");
        labelK.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
        keyboardPanel.add(labelK, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 50, 50));

        labelJ.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        labelJ.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelJ.setText("J");
        labelJ.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
        keyboardPanel.add(labelJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 50, 50));

        labelH.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        labelH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelH.setText("H");
        labelH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
        keyboardPanel.add(labelH, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 50, 50));

        labelG.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        labelG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelG.setText("G");
        labelG.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
        keyboardPanel.add(labelG, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 50, 50));

        labelC.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        labelC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelC.setText("C");
        labelC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
        keyboardPanel.add(labelC, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 50, 50));

        labelX.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        labelX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelX.setText("X");
        labelX.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
        keyboardPanel.add(labelX, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 50, 50));

        labelZ.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        labelZ.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelZ.setText("Z");
        labelZ.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
        keyboardPanel.add(labelZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 50, 50));

        labelD.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        labelD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelD.setText("D");
        labelD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
        keyboardPanel.add(labelD, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 50, 50));

        labelS.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        labelS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelS.setText("S");
        labelS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
        keyboardPanel.add(labelS, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 50, 50));

        labelBackSlash.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        labelBackSlash.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBackSlash.setText("\\");
            labelBackSlash.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
            keyboardPanel.add(labelBackSlash, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 200, 60, 50));

            labelLeftShift.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
            labelLeftShift.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            labelLeftShift.setText("SHIFT");
            labelLeftShift.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
            keyboardPanel.add(labelLeftShift, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 130, 50));

            labelW.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
            labelW.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            labelW.setText("W");
            labelW.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
            keyboardPanel.add(labelW, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 50, 50));

            labelE.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
            labelE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            labelE.setText("E");
            labelE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
            keyboardPanel.add(labelE, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 50, 50));

            labelR.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
            labelR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            labelR.setText("R");
            labelR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
            keyboardPanel.add(labelR, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 50, 50));

            labelT.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
            labelT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            labelT.setText("T");
            labelT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
            keyboardPanel.add(labelT, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 50, 50));

            labelY.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
            labelY.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            labelY.setText("Y");
            labelY.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
            keyboardPanel.add(labelY, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 50, 50));

            labelU.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
            labelU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            labelU.setText("U");
            labelU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
            keyboardPanel.add(labelU, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 50, 50));

            labelI.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
            labelI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            labelI.setText("I");
            labelI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
            keyboardPanel.add(labelI, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 50, 50));

            labelO.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
            labelO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            labelO.setText("O");
            labelO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
            keyboardPanel.add(labelO, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 50, 50));

            labelP.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
            labelP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            labelP.setText("P");
            labelP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
            keyboardPanel.add(labelP, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 50, 50));

            labelOpenBracket.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
            labelOpenBracket.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            labelOpenBracket.setText("[");
            labelOpenBracket.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
            keyboardPanel.add(labelOpenBracket, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, 50, 50));

            labelCloseBracket.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
            labelCloseBracket.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            labelCloseBracket.setText("]");
            labelCloseBracket.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
            keyboardPanel.add(labelCloseBracket, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, 50, 50));

            labelA.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
            labelA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            labelA.setText("A");
            labelA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
            keyboardPanel.add(labelA, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 50, 50));

            labelBefore1.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
            labelBefore1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            labelBefore1.setText("`");
            labelBefore1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
            keyboardPanel.add(labelBefore1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 60, 50));

            label2.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
            label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            label2.setText("2");
            label2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
            keyboardPanel.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 50, 50));

            label3.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
            label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            label3.setText("3");
            label3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
            keyboardPanel.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 50, 50));

            label4.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
            label4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            label4.setText("4");
            label4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
            keyboardPanel.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 50, 50));

            label5.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
            label5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            label5.setText("5");
            label5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
            keyboardPanel.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 50, 50));

            label6.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
            label6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            label6.setText("6");
            label6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
            keyboardPanel.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 50, 50));

            label7.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
            label7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            label7.setText("7");
            label7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
            keyboardPanel.add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 50, 50));

            label8.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
            label8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            label8.setText("8");
            label8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
            keyboardPanel.add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 50, 50));

            label9.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
            label9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            label9.setText("9");
            label9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
            keyboardPanel.add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 50, 50));

            label0.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
            label0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            label0.setText("0");
            label0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
            keyboardPanel.add(label0, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 50, 50));

            labelMinus.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
            labelMinus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            labelMinus.setText("-");
            labelMinus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
            keyboardPanel.add(labelMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, 50, 50));

            labelEquals.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
            labelEquals.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            labelEquals.setText("=");
            labelEquals.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
            keyboardPanel.add(labelEquals, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 140, 50, 50));

            labelBackspace.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
            labelBackspace.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            labelBackspace.setText("Backspace");
            labelBackspace.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
            keyboardPanel.add(labelBackspace, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 140, 90, 50));

            label1.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
            label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            label1.setText("1");
            label1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
            keyboardPanel.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 50, 50));

            labelQ.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
            labelQ.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            labelQ.setText("Q");
            labelQ.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
            keyboardPanel.add(labelQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 50, 50));

            labelTab.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
            labelTab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            labelTab.setText("TAB");
            labelTab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
            keyboardPanel.add(labelTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 90, 50));

            labelCaps.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
            labelCaps.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            labelCaps.setText("CAPS");
            labelCaps.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
            keyboardPanel.add(labelCaps, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 100, 50));

            labelSlash.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
            labelSlash.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            labelSlash.setText("/");
            labelSlash.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));
            keyboardPanel.add(labelSlash, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, 50, 50));

            keyboardKeysPanel.setBackground(new java.awt.Color(255, 0, 102));
            keyboardKeysPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            javax.swing.GroupLayout leftPalmPanelLayout = new javax.swing.GroupLayout(leftPalmPanel);
            leftPalmPanel.setLayout(leftPalmPanelLayout);
            leftPalmPanelLayout.setHorizontalGroup(
                leftPalmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 70, Short.MAX_VALUE)
            );
            leftPalmPanelLayout.setVerticalGroup(
                leftPalmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 60, Short.MAX_VALUE)
            );

            keyboardKeysPanel.add(leftPalmPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 70, 60));

            javax.swing.GroupLayout leftPinkiePanelLayout = new javax.swing.GroupLayout(leftPinkiePanel);
            leftPinkiePanel.setLayout(leftPinkiePanelLayout);
            leftPinkiePanelLayout.setHorizontalGroup(
                leftPinkiePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 10, Short.MAX_VALUE)
            );
            leftPinkiePanelLayout.setVerticalGroup(
                leftPinkiePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 30, Short.MAX_VALUE)
            );

            keyboardKeysPanel.add(leftPinkiePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 10, 30));

            javax.swing.GroupLayout leftRingPanelLayout = new javax.swing.GroupLayout(leftRingPanel);
            leftRingPanel.setLayout(leftRingPanelLayout);
            leftRingPanelLayout.setHorizontalGroup(
                leftRingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 10, Short.MAX_VALUE)
            );
            leftRingPanelLayout.setVerticalGroup(
                leftRingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 50, Short.MAX_VALUE)
            );

            keyboardKeysPanel.add(leftRingPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, 50));

            javax.swing.GroupLayout leftMiddlePanelLayout = new javax.swing.GroupLayout(leftMiddlePanel);
            leftMiddlePanel.setLayout(leftMiddlePanelLayout);
            leftMiddlePanelLayout.setHorizontalGroup(
                leftMiddlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 10, Short.MAX_VALUE)
            );
            leftMiddlePanelLayout.setVerticalGroup(
                leftMiddlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 60, Short.MAX_VALUE)
            );

            keyboardKeysPanel.add(leftMiddlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, -1, 60));

            javax.swing.GroupLayout leftPointerPanelLayout = new javax.swing.GroupLayout(leftPointerPanel);
            leftPointerPanel.setLayout(leftPointerPanelLayout);
            leftPointerPanelLayout.setHorizontalGroup(
                leftPointerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 10, Short.MAX_VALUE)
            );
            leftPointerPanelLayout.setVerticalGroup(
                leftPointerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 40, Short.MAX_VALUE)
            );

            keyboardKeysPanel.add(leftPointerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, 40));

            javax.swing.GroupLayout leftThumbPanelLayout = new javax.swing.GroupLayout(leftThumbPanel);
            leftThumbPanel.setLayout(leftThumbPanelLayout);
            leftThumbPanelLayout.setHorizontalGroup(
                leftThumbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 40, Short.MAX_VALUE)
            );
            leftThumbPanelLayout.setVerticalGroup(
                leftThumbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 10, Short.MAX_VALUE)
            );

            keyboardKeysPanel.add(leftThumbPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 40, 10));

            javax.swing.GroupLayout rightPalmPanelLayout = new javax.swing.GroupLayout(rightPalmPanel);
            rightPalmPanel.setLayout(rightPalmPanelLayout);
            rightPalmPanelLayout.setHorizontalGroup(
                rightPalmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 70, Short.MAX_VALUE)
            );
            rightPalmPanelLayout.setVerticalGroup(
                rightPalmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 60, Short.MAX_VALUE)
            );

            keyboardKeysPanel.add(rightPalmPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 70, 60));

            javax.swing.GroupLayout rightThumbPanelLayout = new javax.swing.GroupLayout(rightThumbPanel);
            rightThumbPanel.setLayout(rightThumbPanelLayout);
            rightThumbPanelLayout.setHorizontalGroup(
                rightThumbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 40, Short.MAX_VALUE)
            );
            rightThumbPanelLayout.setVerticalGroup(
                rightThumbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 10, Short.MAX_VALUE)
            );

            keyboardKeysPanel.add(rightThumbPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, -1, -1));

            javax.swing.GroupLayout rightPointerPanelLayout = new javax.swing.GroupLayout(rightPointerPanel);
            rightPointerPanel.setLayout(rightPointerPanelLayout);
            rightPointerPanelLayout.setHorizontalGroup(
                rightPointerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 10, Short.MAX_VALUE)
            );
            rightPointerPanelLayout.setVerticalGroup(
                rightPointerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 40, Short.MAX_VALUE)
            );

            keyboardKeysPanel.add(rightPointerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, -1, -1));

            javax.swing.GroupLayout rightMiddlePanelLayout = new javax.swing.GroupLayout(rightMiddlePanel);
            rightMiddlePanel.setLayout(rightMiddlePanelLayout);
            rightMiddlePanelLayout.setHorizontalGroup(
                rightMiddlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 10, Short.MAX_VALUE)
            );
            rightMiddlePanelLayout.setVerticalGroup(
                rightMiddlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 60, Short.MAX_VALUE)
            );

            keyboardKeysPanel.add(rightMiddlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, -1, -1));

            javax.swing.GroupLayout rightRingPanelLayout = new javax.swing.GroupLayout(rightRingPanel);
            rightRingPanel.setLayout(rightRingPanelLayout);
            rightRingPanelLayout.setHorizontalGroup(
                rightRingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 10, Short.MAX_VALUE)
            );
            rightRingPanelLayout.setVerticalGroup(
                rightRingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 50, Short.MAX_VALUE)
            );

            keyboardKeysPanel.add(rightRingPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 10, -1));

            javax.swing.GroupLayout rightPinkiePanelLayout = new javax.swing.GroupLayout(rightPinkiePanel);
            rightPinkiePanel.setLayout(rightPinkiePanelLayout);
            rightPinkiePanelLayout.setHorizontalGroup(
                rightPinkiePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 10, Short.MAX_VALUE)
            );
            rightPinkiePanelLayout.setVerticalGroup(
                rightPinkiePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 30, Short.MAX_VALUE)
            );

            keyboardKeysPanel.add(rightPinkiePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, -1, -1));

            keyboardPanel.add(keyboardKeysPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

            typingPanel.setBackground(new java.awt.Color(0, 0, 0));
            typingPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            colorTextPane.setEditable(false);
            colorTextPane.setBorder(null);
            colorTextPane.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
            colorTextPane.setFocusable(false);
            colorTextPane.setHighlighter(null);
            jScrollPane2.setViewportView(colorTextPane);

            typingPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 933, 83));

            textPaneArea.setEditable(false);
            textPaneArea.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
            jScrollPane3.setViewportView(textPaneArea);

            typingPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 29, 933, 280));

            wpmLabel.setForeground(new java.awt.Color(255, 255, 255));
            wpmLabel.setText("wpm:");
            typingPanel.add(wpmLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 1, 101, 23));

            tipsLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
            tipsLabel.setForeground(new java.awt.Color(255, 255, 255));
            tipsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            tipsLabel.setText("Click here for tips!");
            typingPanel.add(tipsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 430, 110, -1));

            sentenceRadioButton.setBackground(new java.awt.Color(0, 0, 0));
            sentenceRadioButton.setForeground(new java.awt.Color(255, 255, 255));
            sentenceRadioButton.setText("Practice Typing Sentences");
            sentenceRadioButton.addFocusListener(new java.awt.event.FocusAdapter() {
                public void focusGained(java.awt.event.FocusEvent evt) {
                    sentenceRadioButtonFocusGained(evt);
                }
            });
            typingPanel.add(sentenceRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

            uppercaseRadioButton.setBackground(new java.awt.Color(0, 0, 0));
            uppercaseRadioButton.setForeground(new java.awt.Color(255, 255, 255));
            uppercaseRadioButton.setText("Practice Uppercase Words");
            uppercaseRadioButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    uppercaseRadioButtonActionPerformed(evt);
                }
            });
            typingPanel.add(uppercaseRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 410, -1, -1));

            lowercaseRadioButton.setBackground(new java.awt.Color(0, 0, 0));
            lowercaseRadioButton.setForeground(new java.awt.Color(255, 255, 255));
            lowercaseRadioButton.setText("Practice Lowercase Words");
            lowercaseRadioButton.setOpaque(false);
            typingPanel.add(lowercaseRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 170, -1));

            symbolRadioButton.setBackground(new java.awt.Color(0, 0, 0));
            symbolRadioButton.setForeground(new java.awt.Color(255, 255, 255));
            symbolRadioButton.setText("Practice Symbols");
            typingPanel.add(symbolRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, 126, -1));

            numberRadioButton.setBackground(new java.awt.Color(0, 0, 0));
            numberRadioButton.setForeground(new java.awt.Color(255, 255, 255));
            numberRadioButton.setText("Practice Numbers");
            typingPanel.add(numberRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 124, -1));

            userTextField.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
            userTextField.setOpaque(false);
            userTextField.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    userTextFieldActionPerformed(evt);
                }
            });
            typingPanel.add(userTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 499, 17, 0));
            userTextField.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 0));

            clickAboveLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
            clickAboveLabel.setForeground(new java.awt.Color(255, 255, 255));
            clickAboveLabel.setText("Click above to start typing");
            typingPanel.add(clickAboveLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 410, -1, -1));

            customTextRadioButton.setForeground(new java.awt.Color(255, 255, 255));
            customTextRadioButton.setText("Practice Custom Text");
            customTextRadioButton.setOpaque(false);
            typingPanel.add(customTextRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

            trueAccuracyLable.setForeground(new java.awt.Color(255, 255, 255));
            trueAccuracyLable.setText("Accuracy:");
            typingPanel.add(trueAccuracyLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 5, 184, -1));

            javax.swing.GroupLayout typingPanelHostPanelLayout = new javax.swing.GroupLayout(typingPanelHostPanel);
            typingPanelHostPanel.setLayout(typingPanelHostPanelLayout);
            typingPanelHostPanelLayout.setHorizontalGroup(
                typingPanelHostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(keyboardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(typingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            );
            typingPanelHostPanelLayout.setVerticalGroup(
                typingPanelHostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, typingPanelHostPanelLayout.createSequentialGroup()
                    .addComponent(typingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(keyboardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0))
            );

            getContentPane().add(typingPanelHostPanel);
            getContentPane().add(jLabel1);
            getContentPane().add(jLabel2);

            loginSignUpPanel.setBackground(new java.awt.Color(0, 0, 0));

            loginSignUpLabel.setFont(new java.awt.Font("NSimSun", 1, 48)); // NOI18N
            loginSignUpLabel.setForeground(new java.awt.Color(255, 255, 255));
            loginSignUpLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            loginSignUpLabel.setText("Login/SignUp");

            usernameLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
            usernameLabel.setForeground(new java.awt.Color(255, 255, 255));
            usernameLabel.setText("Username:");

            passwordLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
            passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
            passwordLabel.setText("Password:");

            loginButton.setFont(new java.awt.Font("NSimSun", 1, 24)); // NOI18N
            loginButton.setText("Login");

            signUpButton.setFont(new java.awt.Font("NSimSun", 1, 24)); // NOI18N
            signUpButton.setText("SignUp");

            javax.swing.GroupLayout loginSignUpPanelLayout = new javax.swing.GroupLayout(loginSignUpPanel);
            loginSignUpPanel.setLayout(loginSignUpPanelLayout);
            loginSignUpPanelLayout.setHorizontalGroup(
                loginSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginSignUpPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(loginSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(passwordLabel)
                        .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(loginSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginSignUpPanelLayout.createSequentialGroup()
                            .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(signUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap())
                .addComponent(loginSignUpLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            loginSignUpPanelLayout.setVerticalGroup(
                loginSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginSignUpPanelLayout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(loginSignUpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(loginSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(28, 28, 28)
                    .addGroup(loginSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(passwordLabel))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(loginSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(signUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(127, Short.MAX_VALUE))
            );

            getContentPane().add(loginSignUpPanel);

            settingsPanel.setBackground(new java.awt.Color(0, 0, 0));

            lightModeRadioButton.setBackground(new java.awt.Color(0, 0, 0));
            colorModeButtonGroup.add(lightModeRadioButton);
            lightModeRadioButton.setForeground(new java.awt.Color(255, 255, 255));
            lightModeRadioButton.setText("Light Mode");

            darkModeRadioButton.setBackground(new java.awt.Color(0, 0, 0));
            colorModeButtonGroup.add(darkModeRadioButton);
            darkModeRadioButton.setForeground(new java.awt.Color(255, 255, 255));
            darkModeRadioButton.setText("Dark Mode");

            stringLengthSlider.setBackground(new java.awt.Color(0, 0, 0));
            stringLengthSlider.setForeground(new java.awt.Color(0, 0, 0));
            stringLengthSlider.setMaximum(1000);
            stringLengthSlider.setMinimum(5);
            stringLengthSlider.setValue(500);
            stringLengthSlider.setOpaque(false);

            stringLengthSliderLabel.setForeground(new java.awt.Color(255, 255, 255));
            stringLengthSliderLabel.setText("Approximate text length to generate:");

            typingSoundsVolumeSlider.setBackground(new java.awt.Color(0, 0, 0));
            typingSoundsVolumeSlider.setMaximum(6);
            typingSoundsVolumeSlider.setMinimum(-80);
            typingSoundsVolumeSlider.setValue(-8);
            typingSoundsVolumeSlider.setOpaque(false);

            typingSoundsVolumeSliderLabel.setForeground(new java.awt.Color(255, 255, 255));
            typingSoundsVolumeSliderLabel.setText("Typing sounds volume:");

            textDisplaySizeSlider.setBackground(new java.awt.Color(0, 0, 0));
            textDisplaySizeSlider.setMaximum(70);
            textDisplaySizeSlider.setMinimum(15);
            textDisplaySizeSlider.setValue(30);

            textDisplaySizeSliderLabel.setForeground(new java.awt.Color(255, 255, 255));
            textDisplaySizeSliderLabel.setText("Text display size:");

            typedTextSizeSliderLabel.setBackground(new java.awt.Color(255, 255, 255));
            typedTextSizeSliderLabel.setForeground(new java.awt.Color(255, 255, 255));
            typedTextSizeSliderLabel.setText("Text typed size:");

            typedTextSizeSlider.setBackground(new java.awt.Color(0, 0, 0));
            typedTextSizeSlider.setMaximum(60);
            typedTextSizeSlider.setMinimum(15);
            typedTextSizeSlider.setValue(30);

            errorSoundsVolumeSliderLabel.setForeground(new java.awt.Color(255, 255, 255));
            errorSoundsVolumeSliderLabel.setText("Error sounds volume:");

            errorSoundsVolumeSlider.setBackground(new java.awt.Color(0, 0, 0));
            errorSoundsVolumeSlider.setMaximum(6);
            errorSoundsVolumeSlider.setMinimum(-80);
            errorSoundsVolumeSlider.setValue(-8);
            errorSoundsVolumeSlider.setOpaque(false);

            lofiStreamVolumeSliderLabel.setForeground(new java.awt.Color(255, 255, 255));
            lofiStreamVolumeSliderLabel.setText("Lofi stream volume:");

            lofiStreamVolumeSlider.setBackground(new java.awt.Color(0, 0, 0));
            lofiStreamVolumeSlider.setMaximum(6);
            lofiStreamVolumeSlider.setMinimum(-80);
            lofiStreamVolumeSlider.setValue(3);
            lofiStreamVolumeSlider.setOpaque(false);

            streamLofiButton.setBackground(new java.awt.Color(0, 0, 0));
            streamLofiButton.setForeground(new java.awt.Color(255, 255, 255));
            streamLofiButton.setText("Stream Lofi");

            resetSettingsButton.setText("Reset Settings");

            keyboardVisualRadioButton.setForeground(new java.awt.Color(255, 255, 255));
            keyboardVisualRadioButton.setText("Enable Keyboard Visual");
            keyboardVisualRadioButton.setOpaque(false);

            javax.swing.GroupLayout settingsPanelLayout = new javax.swing.GroupLayout(settingsPanel);
            settingsPanel.setLayout(settingsPanelLayout);
            settingsPanelLayout.setHorizontalGroup(
                settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(settingsPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(settingsPanelLayout.createSequentialGroup()
                            .addComponent(darkModeRadioButton)
                            .addGap(18, 18, 18)
                            .addComponent(keyboardVisualRadioButton))
                        .addGroup(settingsPanelLayout.createSequentialGroup()
                            .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(stringLengthSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(typingSoundsVolumeSliderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(typingSoundsVolumeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(errorSoundsVolumeSliderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(errorSoundsVolumeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(52, 52, 52)
                            .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(typedTextSizeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(typedTextSizeSliderLabel)
                                .addComponent(textDisplaySizeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textDisplaySizeSliderLabel)
                                .addComponent(lofiStreamVolumeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(settingsPanelLayout.createSequentialGroup()
                            .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(stringLengthSliderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(settingsPanelLayout.createSequentialGroup()
                                    .addComponent(lightModeRadioButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(streamLofiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lofiStreamVolumeSliderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(resetSettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            settingsPanelLayout.setVerticalGroup(
                settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(settingsPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lightModeRadioButton)
                        .addComponent(streamLofiButton)
                        .addComponent(resetSettingsButton))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(darkModeRadioButton)
                        .addComponent(keyboardVisualRadioButton))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingsPanelLayout.createSequentialGroup()
                            .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(stringLengthSliderLabel)
                                .addComponent(lofiStreamVolumeSliderLabel))
                            .addGap(4, 4, 4)
                            .addComponent(stringLengthSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lofiStreamVolumeSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(typingSoundsVolumeSliderLabel)
                        .addComponent(textDisplaySizeSliderLabel))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(typingSoundsVolumeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textDisplaySizeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(errorSoundsVolumeSliderLabel)
                        .addComponent(typedTextSizeSliderLabel))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(errorSoundsVolumeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(typedTextSizeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(37, 37, 37))
            );

            getContentPane().add(settingsPanel);

            customTextPanel.setBackground(new java.awt.Color(0, 0, 0));

            customTextLabel.setFont(new java.awt.Font("NSimSun", 1, 48)); // NOI18N
            customTextLabel.setForeground(new java.awt.Color(255, 255, 255));
            customTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            customTextLabel.setText("Add Custom Text");

            customTextButton.setFont(new java.awt.Font("NSimSun", 1, 36)); // NOI18N
            customTextButton.setText("Save Text");

            customTextTextArea.setColumns(20);
            customTextTextArea.setRows(5);
            jScrollPane1.setViewportView(customTextTextArea);

            descriptionLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            descriptionLabel.setForeground(new java.awt.Color(255, 255, 255));
            descriptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            descriptionLabel.setText("Type in the box above to add words/sentences. Each line represents a word/sentence which will be randomly generated.");

            javax.swing.GroupLayout customTextPanelLayout = new javax.swing.GroupLayout(customTextPanel);
            customTextPanel.setLayout(customTextPanelLayout);
            customTextPanelLayout.setHorizontalGroup(
                customTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1)
                .addComponent(customTextLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customTextPanelLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customTextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(115, 115, 115))
                .addComponent(descriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE)
            );
            customTextPanelLayout.setVerticalGroup(
                customTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(customTextPanelLayout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(customTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addGap(18, 18, 18)
                    .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(customTextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(45, 45, 45))
            );

            getContentPane().add(customTextPanel);

            logoutPanel.setBackground(new java.awt.Color(0, 0, 0));

            logoutButton.setFont(new java.awt.Font("NSimSun", 1, 24)); // NOI18N
            logoutButton.setText("Logout");
            logoutButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    logoutButtonActionPerformed(evt);
                }
            });

            savePreferencesButton.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
            savePreferencesButton.setText("Save Preferences");

            javax.swing.GroupLayout logoutPanelLayout = new javax.swing.GroupLayout(logoutPanel);
            logoutPanel.setLayout(logoutPanelLayout);
            logoutPanelLayout.setHorizontalGroup(
                logoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(logoutPanelLayout.createSequentialGroup()
                    .addGroup(logoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(savePreferencesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(logoutPanelLayout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 10, Short.MAX_VALUE))
            );
            logoutPanelLayout.setVerticalGroup(
                logoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(logoutPanelLayout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(savePreferencesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(47, 47, 47))
            );

            getContentPane().add(logoutPanel);

            buttonGroupPanel.setBackground(new java.awt.Color(0, 0, 0));

            shapePanel.setBackground(new java.awt.Color(0, 0, 0));
            shapePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            loginSignUpButton.setText("Click To Open Account Page");
            shapePanel.add(loginSignUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 231, -1));

            settingsButton.setBackground(new java.awt.Color(0, 0, 0));
            settingsButton.setForeground(new java.awt.Color(255, 255, 255));
            settingsButton.setText("Click To Open Settings");
            shapePanel.add(settingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 231, -1));

            getNewTextButton.setBackground(new java.awt.Color(0, 0, 0));
            getNewTextButton.setForeground(new java.awt.Color(255, 255, 255));
            getNewTextButton.setText("Get New Text");
            getNewTextButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    getNewTextButtonActionPerformed(evt);
                }
            });
            shapePanel.add(getNewTextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 230, -1));

            customTextPanelButton.setText("Click To Open Custom Text Panel");
            customTextPanelButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    customTextPanelButtonActionPerformed(evt);
                }
            });
            shapePanel.add(customTextPanelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 230, -1));

            javax.swing.GroupLayout buttonGroupPanelLayout = new javax.swing.GroupLayout(buttonGroupPanel);
            buttonGroupPanel.setLayout(buttonGroupPanelLayout);
            buttonGroupPanelLayout.setHorizontalGroup(
                buttonGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(buttonGroupPanelLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(shapePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
            );
            buttonGroupPanelLayout.setVerticalGroup(
                buttonGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(buttonGroupPanelLayout.createSequentialGroup()
                    .addComponent(shapePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 4, Short.MAX_VALUE))
            );

            getContentPane().add(buttonGroupPanel);

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void userTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTextFieldActionPerformed

    private void sentenceRadioButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sentenceRadioButtonFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_sentenceRadioButtonFocusGained

    private void uppercaseRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uppercaseRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uppercaseRadioButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void customTextPanelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customTextPanelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customTextPanelButtonActionPerformed

    private void getNewTextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getNewTextButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getNewTextButtonActionPerformed
    // WARNING: Do NOT modify or write any code in this file!
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel buttonGroupPanel;
    public javax.swing.JLabel clickAboveLabel;
    public javax.swing.ButtonGroup colorModeButtonGroup;
    public javax.swing.JTextPane colorTextPane;
    public javax.swing.JButton customTextButton;
    public javax.swing.JLabel customTextLabel;
    public javax.swing.JPanel customTextPanel;
    public javax.swing.JToggleButton customTextPanelButton;
    public javax.swing.JRadioButton customTextRadioButton;
    public javax.swing.JTextArea customTextTextArea;
    public javax.swing.JRadioButton darkModeRadioButton;
    public javax.swing.JLabel descriptionLabel;
    public javax.swing.JSlider errorSoundsVolumeSlider;
    public javax.swing.JLabel errorSoundsVolumeSliderLabel;
    public javax.swing.JButton getNewTextButton;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JPanel keyboardKeysPanel;
    public javax.swing.JPanel keyboardPanel;
    public javax.swing.JRadioButton keyboardVisualRadioButton;
    public javax.swing.JLabel label0;
    public javax.swing.JLabel label1;
    public javax.swing.JLabel label2;
    public javax.swing.JLabel label3;
    public javax.swing.JLabel label4;
    public javax.swing.JLabel label5;
    public javax.swing.JLabel label6;
    public javax.swing.JLabel label7;
    public javax.swing.JLabel label8;
    public javax.swing.JLabel label9;
    public javax.swing.JLabel labelA;
    public javax.swing.JLabel labelApostrophe;
    public javax.swing.JLabel labelB;
    public javax.swing.JLabel labelBackSlash;
    public javax.swing.JLabel labelBackspace;
    public javax.swing.JLabel labelBefore1;
    public javax.swing.JLabel labelC;
    public javax.swing.JLabel labelCaps;
    public javax.swing.JLabel labelCloseBracket;
    public javax.swing.JLabel labelComma;
    public javax.swing.JLabel labelD;
    public javax.swing.JLabel labelE;
    public javax.swing.JLabel labelEnter;
    public javax.swing.JLabel labelEquals;
    public javax.swing.JLabel labelF;
    public javax.swing.JLabel labelFn;
    public javax.swing.JLabel labelG;
    public javax.swing.JLabel labelH;
    public javax.swing.JLabel labelI;
    public javax.swing.JLabel labelJ;
    public javax.swing.JLabel labelK;
    public javax.swing.JLabel labelL;
    public javax.swing.JLabel labelLeftAlt;
    public javax.swing.JLabel labelLeftCtrl;
    public javax.swing.JLabel labelLeftShift;
    public javax.swing.JLabel labelLines;
    public javax.swing.JLabel labelM;
    public javax.swing.JLabel labelMinus;
    public javax.swing.JLabel labelN;
    public javax.swing.JLabel labelO;
    public javax.swing.JLabel labelOpenBracket;
    public javax.swing.JLabel labelP;
    public javax.swing.JLabel labelPeriod;
    public javax.swing.JLabel labelQ;
    public javax.swing.JLabel labelR;
    public javax.swing.JLabel labelRightAlt;
    public javax.swing.JLabel labelRightCtrl;
    public javax.swing.JLabel labelRightShift;
    public javax.swing.JLabel labelS;
    public javax.swing.JLabel labelSemicolon;
    public javax.swing.JLabel labelSlash;
    public javax.swing.JLabel labelSpace;
    public javax.swing.JLabel labelT;
    public javax.swing.JLabel labelTab;
    public javax.swing.JLabel labelU;
    public javax.swing.JLabel labelV;
    public javax.swing.JLabel labelW;
    public javax.swing.JLabel labelWindows;
    public javax.swing.JLabel labelX;
    public javax.swing.JLabel labelY;
    public javax.swing.JLabel labelZ;
    public javax.swing.JPanel leftMiddlePanel;
    public javax.swing.JPanel leftPalmPanel;
    public javax.swing.JPanel leftPinkiePanel;
    public javax.swing.JPanel leftPointerPanel;
    public javax.swing.JPanel leftRingPanel;
    public javax.swing.JPanel leftThumbPanel;
    public javax.swing.JRadioButton lightModeRadioButton;
    public javax.swing.JSlider lofiStreamVolumeSlider;
    public javax.swing.JLabel lofiStreamVolumeSliderLabel;
    public javax.swing.JButton loginButton;
    public javax.swing.JToggleButton loginSignUpButton;
    public javax.swing.JLabel loginSignUpLabel;
    public javax.swing.JPanel loginSignUpPanel;
    public javax.swing.JButton logoutButton;
    public javax.swing.JPanel logoutPanel;
    public javax.swing.JRadioButton lowercaseRadioButton;
    public javax.swing.JRadioButton numberRadioButton;
    public javax.swing.JPasswordField passwordField;
    public javax.swing.JLabel passwordLabel;
    public javax.swing.JButton resetSettingsButton;
    public javax.swing.JPanel rightMiddlePanel;
    public javax.swing.JPanel rightPalmPanel;
    public javax.swing.JPanel rightPinkiePanel;
    public javax.swing.JPanel rightPointerPanel;
    public javax.swing.JPanel rightRingPanel;
    public javax.swing.JPanel rightThumbPanel;
    public javax.swing.JButton savePreferencesButton;
    public javax.swing.JRadioButton sentenceRadioButton;
    public javax.swing.JToggleButton settingsButton;
    public javax.swing.JPanel settingsPanel;
    public javax.swing.JPanel shapePanel;
    public javax.swing.JButton signUpButton;
    public javax.swing.JToggleButton streamLofiButton;
    public javax.swing.JSlider stringLengthSlider;
    public javax.swing.JLabel stringLengthSliderLabel;
    public javax.swing.JRadioButton symbolRadioButton;
    public javax.swing.JSlider textDisplaySizeSlider;
    public javax.swing.JLabel textDisplaySizeSliderLabel;
    public javax.swing.JTextPane textPaneArea;
    public javax.swing.JLabel tipsLabel;
    public javax.swing.JLabel trueAccuracyLable;
    public javax.swing.JSlider typedTextSizeSlider;
    public javax.swing.JLabel typedTextSizeSliderLabel;
    public javax.swing.JPanel typingPanel;
    public javax.swing.JPanel typingPanelHostPanel;
    public javax.swing.JSlider typingSoundsVolumeSlider;
    public javax.swing.JLabel typingSoundsVolumeSliderLabel;
    public javax.swing.JRadioButton uppercaseRadioButton;
    public javax.swing.JTextField userTextField;
    public javax.swing.JTextField usernameField;
    public javax.swing.JLabel usernameLabel;
    public javax.swing.JLabel wpmLabel;
    // End of variables declaration//GEN-END:variables
}
